### ISSUE TITLE
刚刚接触openwrt请问这个怎么安装呢

### ISSUE THREAD

**Issue by jackberry** [animefansxj/luci-app-smartinfo#1]
刚刚接触openwrt请问这个怎么安装呢

**Comment by animefansxj** [comment]
1.将文件按结构放入openwrt的 feeds/luci 目录中
2.执行 ./scripts/feeds install -a
3.执行 make menuconfig，到 LuCI/Applications 下选中luci-app-smartinfo，会自动选中smartmontools软件包
4.编译
